Create RTSPtoWeb.yaml
bigbeartechworld/big-bear-casaos pull request #9
Opened 2023-11-07 01:51 UTC by thedroidkid

Added RTSPtoWeb app

2023-11-07 03:45 UTC, dragonfire1119 requested changes
Can you add this app to the README.md app list?

2023-11-07 03:45 UTC, dragonfire1119 commented on Apps/RTSPtoWeb/RTSPtoWeb.yaml
> +              target: /tmp
You would need to add

```
x-casaos: # CasaOS specific configuration
      volumes:
        - container: /tmp
          description:
            en_us: "Container Path: /tmp"
        - container: /app/public/icons
          description:
            en_us: "Container Path: /app/public/icons"
      ports:
        - container: "8083"
          description:
            en_us: "Container Port: 8083"
```

2023-11-07 03:45 UTC, dragonfire1119 commented on Apps/RTSPtoWeb/RTSPtoWeb.yaml
> +x-casaos:
Can you look at: https://github.com/bigbeartechworld/big-bear-casaos/blob/8e00ebbee8eb936f1a44f888beea8a26570d06d1/Apps/homarr/docker-compose.yml#L49

2023-11-09 02:56 UTC, thedroidkid commented
The problem with this is config.json is stored in /dist/config.json but when I try setting the volume /DATA/AppData/rtsp-to-web to /dist the container will not start no matter what I do. For now I just mapped it to /tmp cuz I just manually copy the config over its a real pain

2023-11-11 15:51 UTC, dragonfire1119 commented
@thedroidkid Yeah, it needs to be made easier to install. I'll look at it more when I have time.

2024-05-04 16:09 UTC, closed without merging